# Config file for `air` - a live reloading tool for Go applications.

[build]
# Working directory
cmd = "go build -o main.exe ."
bin = "./main.exe"  # Use ./ for Windows
dir = "."

# Watch files with the following extensions
include_ext = ["go", "tmpl", "templ"]

# Exclude the following files/directories
exclude_dir = ["vendor", "node_modules"]

[log]
level = "debug"
time = true
color = true

[runner]
# Command to run the templ generation tool
cmd = "templ generate"
# Run the templ generation tool before the main command
pre = true

[watch]
# Directories to watch for changes
dirs = ["."]
# Files to watch for changes
files = ["**/*.go", "**/*.tmpl", "**/*.templ"]
# Exclude directories from being watched
exclude = ["vendor", "node_modules"]

# Ensure the runner is executed before running the build command
pre_build = "templ generate"
