version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: shiva7
      MYSQL_DATABASE: blogflex
      MYSQL_USER: andrenormanlang
      MYSQL_PASSWORD: shiva7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
