services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shiva7
      POSTGRES_DB: blogflex
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: postgres
      DB_PASSWORD: shiva7
      DB_NAME: blogflex
      DB_PORT: 5432
      HASURA_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_ENDPOINT: ${HASURA_ENDPOINT}
    volumes:
      - ./.env:/app/.env
    depends_on: []

volumes:
  db_data:
