services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    environment:
      DB_SSL_MODE: require
    volumes:
      - ../.env:/app/.env
      - ../credentials:/app/credentials
